import type {
  Property,
  PropertyMedia,
  PropertyDetails,
  RLAAssessment,
  AreaOverview,
  Review,
} from "@/lib/types";

export const PLACEHOLDER_PROPERTIES: Property[] = [
  {
    id: "1",
    slug: "modern-2br-scandinavian-senayan",
    title: "Modern 2BR Scandinavian Apartment",
    title_id: "Apartemen Skandinavia 2KT Modern",
    area: "Senayan",
    district: "South Jakarta",
    property_type: "apartment",
    price_per_month: 6500000,
    bedrooms: 2,
    bathrooms: 2,
    size_sqm: 60,
    available_from: "2025-07-01",
    min_stay_months: 3,
    status: "live",
    submission_type: "curated",
    is_featured: true,
    published_at: "2025-06-01",
    thumbnail_url: undefined,
    rla_score: 4.2,
  },
  {
    id: "2",
    slug: "executive-studio-scbd",
    title: "Executive Studio SCBD",
    title_id: "Studio Eksekutif SCBD",
    area: "SCBD",
    district: "South Jakarta",
    property_type: "apartment",
    price_per_month: 12000000,
    bedrooms: 1,
    bathrooms: 1,
    size_sqm: 45,
    available_from: "2025-07-15",
    min_stay_months: 3,
    status: "live",
    submission_type: "curated",
    is_featured: true,
    published_at: "2025-06-01",
    thumbnail_url: undefined,
    rla_score: 4.8,
  },
  {
    id: "3",
    slug: "garden-terrace-suite-menteng",
    title: "Garden Terrace Suite",
    title_id: "Suite Teras Taman",
    area: "Menteng",
    district: "Central Jakarta",
    property_type: "apartment",
    price_per_month: 15500000,
    bedrooms: 2,
    bathrooms: 2,
    size_sqm: 85,
    available_from: "2025-08-01",
    min_stay_months: 6,
    status: "live",
    submission_type: "curated",
    is_featured: false,
    published_at: "2025-06-02",
    thumbnail_url: undefined,
    rla_score: 4.5,
  },
  {
    id: "4",
    slug: "minimalist-loft-senayan",
    title: "Minimalist Loft Senayan",
    title_id: "Loft Minimalis Senayan",
    area: "Senayan",
    district: "South Jakarta",
    property_type: "apartment",
    price_per_month: 8200000,
    bedrooms: 1,
    bathrooms: 1,
    size_sqm: 55,
    available_from: "2025-07-01",
    min_stay_months: 3,
    status: "live",
    submission_type: "curated",
    is_featured: false,
    published_at: "2025-06-03",
    thumbnail_url: undefined,
    rla_score: 4.0,
  },
  {
    id: "5",
    slug: "contemporary-villa-kemang",
    title: "Contemporary Kemang Villa",
    title_id: "Vila Kontemporer Kemang",
    area: "Kemang",
    district: "South Jakarta",
    property_type: "villa",
    price_per_month: 19000000,
    bedrooms: 3,
    bathrooms: 2,
    size_sqm: 180,
    available_from: "2025-07-01",
    min_stay_months: 6,
    status: "live",
    submission_type: "curated",
    is_featured: false,
    published_at: "2025-06-04",
    thumbnail_url: undefined,
    rla_score: 4.9,
  },
  {
    id: "6",
    slug: "luxury-1br-suite-kuningan",
    title: "Luxury 1BR Suite",
    title_id: "Suite 1KT Mewah",
    area: "Kuningan",
    district: "South Jakarta",
    property_type: "apartment",
    price_per_month: 10500000,
    bedrooms: 1,
    bathrooms: 1,
    size_sqm: 52,
    available_from: "2025-07-01",
    min_stay_months: 3,
    status: "live",
    submission_type: "curated",
    is_featured: false,
    published_at: "2025-06-05",
    thumbnail_url: undefined,
    rla_score: 4.7,
  },
];

export const PLACEHOLDER_PROPERTY_MEDIA: PropertyMedia[] = [
  {
    id: "m1",
    property_id: "1",
    url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
    media_type: "photo",
    is_primary: true,
    order_index: 0,
  },
];

export const PLACEHOLDER_PROPERTY_DETAILS: PropertyDetails = {
  property_id: "1",
  furnished: "full",
  has_ac: true,
  has_wifi: true,
  has_parking: false,
  has_gym: false,
  has_pool: false,
  has_kitchen: true,
  contract_type: "Independent Lease",
  utilities_included: ["Water", "Internet (Fiber)"],
  utilities_excluded: ["Electricity (Token)", "Laundry/Cleaning"],
  house_rules: ["No pets", "No smoking indoors", "Guests until 10 PM"],
  facilities: ["AC", "WiFi", "Shared Kitchen", "Motor Parking"],
  pros: [
    "Location near MRT (7 min walk)",
    "New building (Built 2023)",
    "24-hour security & gated access",
  ],
  cons: [
    "No elevator (3rd floor walkup)",
    "Cleaning not included in rent",
    "Limited parking (Motorcycle only)",
  ],
};

export const PLACEHOLDER_RLA: RLAAssessment = {
  property_id: "1",
  rla_score: 4.2,
  building_condition: 4,
  natural_lighting: 4,
  bathroom: 3,
  ventilation: 4,
  noise_level: "Quiet",
  security_level: "High",
  assessor_notes:
    "Third floor walkup, no elevator. Building well-maintained. Noise minimal. Highly recommended for young professionals who prefer a quiet environment.",
  assessed_at: "2025-05-15",
};

export const PLACEHOLDER_AREA: AreaOverview = {
  area_slug: "senayan",
  name: "Senayan",
  description:
    "Quiet mixed residential neighborhood, close to major landmarks and transport.",
  expat_friendly: true,
  nearby: [
    { name: "MRT Senayan", distance: "7 min walk" },
    { name: "TransJakarta", distance: "5 min walk" },
    { name: "SCBD District", distance: "12 min drive" },
    { name: "Indomaret", distance: "2 min walk" },
  ],
  vibe_tags: ["Quiet", "Professional", "Well-connected"],
};

export const PLACEHOLDER_REVIEWS: Review[] = [
  {
    id: "r1",
    property_id: "1",
    reviewer_name: "Marcus G.",
    rating: 5,
    comment:
      "Perfect for my first year in Jakarta. The staff were very helpful and the fiber internet is reliable for remote work.",
    moderation_status: "approved",
    created_at: "2024-03-15",
  },
  {
    id: "r2",
    property_id: "1",
    reviewer_name: "Elena P.",
    rating: 4,
    comment:
      "Clean and modern. The lack of elevator is okay, good exercise. But the location really can't be beaten for this price.",
    moderation_status: "approved",
    created_at: "2024-01-20",
  },
];
